name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.1", "8.2", "8.3" ]
        composer_flags: [ "", "--prefer-lowest" ]
        symfony_version: [ "6.*", "7.*" ]
        exclude:
          - php: "8.1"
            symfony_version: "7.*"
    name: 'Build & validate: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony_version }} ${{ matrix.composer_flags}}'
    env:
        PHP: ${{ matrix.php }}
        COMPOSER_MEMORY_LIMIT: -1
        COMPOSER_FLAGS: ${{ matrix.composer_flags }}
        SYMFONY_VERSION: ${{ matrix.symfony_version }}
        PHP_VERSION: ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug, zip
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_READONLY_TOKEN }}
      - name: Install dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.REPO_READ_ONLY_TOKEN }}"}}'
        run: |
          if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
          composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
      - name: Static analysis with PHPStan
        run: composer checktype-ci
      - name: Coding style PSR12 Check
        run: composer checkstyle
      - name: Execute tests (Unit and Feature)
        run: composer test-report-ci
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: ${{ matrix.php == '8.3' &&  matrix.symfony_version == '7.*' &&  matrix.composer_flags == '' }}
        with:
          name: reports
          path: |
            report-phpunit.xml
            coverage-phpunit.xml

  sonar:
    name: 'SonarCloud'
    runs-on: ubuntu-22.04
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: reports
      - name: Run SonarQube scan
        uses: minvws/action-sonarqube@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
